export const Svg = 'svg';
export const Path = 'path';
export const Circle = 'circle';
export const Rect = 'rect';
export const G = 'g';
export const Defs = 'defs';
export const LinearGradient = 'linearGradient';
export const Stop = 'stop';
export const ClipPath = 'clipPath';
export default Svg;
